const PREFIX = 'MASTER_DISCOUNT_';

export const MASTER_DISCOUNT_PAGE_REQUEST = `${PREFIX}PAGE_REQUEST`;

export const MASTER_DISCOUNT_SET_CUSTOMERS = `${PREFIX}SET_CUSTOMERS`;

export const MASTER_DISCOUNT_SET_DISCOUNTS = `${PREFIX}SET_DISCOUNTS`;
